{"uuid":"e2b99f34-1c8b-4ca4-a9fb-78113a9e5418","historyId":"f0ec93346ae20d1cdc945c5c20a91677","fullName":"tests.Login_Test_Detailed.TC_05","labels":[{"name":"package","value":"tests.Login_Test_Detailed"},{"name":"testClass","value":"tests.Login_Test_Detailed"},{"name":"testMethod","value":"TC_05"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"FreshStart3"},{"name":"subSuite","value":"tests.Login_Test_Detailed"},{"name":"host","value":"DESKTOP-L8JH3DS"},{"name":"thread","value":"23432@DESKTOP-L8JH3DS.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"feature","value":"Login Variants"},{"name":"story","value":"TC_05 - error_user login"},{"name":"epic","value":"Login Feature"},{"name":"severity","value":"normal"}],"links":[],"name":"Login with error_user","status":"passed","statusDetails":{"known":false,"muted":false,"flaky":false},"stage":"finished","description":"Login attempt with error_user credentials","steps":[],"attachments":[],"parameters":[],"start":1746766370015,"stop":1746766370336}